### ISSUE TITLE
RouteNavigationPayload is not serializable

### ISSUE THREAD

**Issue by s-ve** [vsavkin/router-store#10]
Currently, `RouteNavigationPayload` stores a reference to a `RouterStateSnapshot` instance.

`RouterStateSnapshot` is likely to contain circular references  (e.g. child routes have pointers to their parent) and thus it cannot be encoded as a JSON string properly.

Wouldn't this problem prevent navigation actions from being serialized and "replayed" at a later point in time ?

**Comment by mkennedy3000** [comment]
If I am correct @vsavkin, all further development for this will be done inside `@ngrx/platform` in the `@ngrx/router-store` module. If this is still an issue I would raise it there and close this one.

**Comment by vsavkin** [comment]
Yup, could you open the issue in @ngrx/platform? 

I'll update the project's readme to point everyone to @ngrx/platform

**Comment by s-ve** [comment]
I've opened a new issue [here](https://github.com/ngrx/platform/issues/27).
